### ISSUE TITLE
Table does not recall the wavetable on load

### ISSUE THREAD

**Issue by Petervos2018** [IggyLabs/IggyLabsModules#13]
Hi Iggy,
As the title says, when you reload a project, (or continue with one after closing rack) no wavefile is loaded.
W10

Greetings Peter.

**Comment by isabelgk** [comment]
Hi Peter, thanks for bringing to my attention! I found the typo causing this, and it should be fixed in the library soon.

**Comment by isabelgk** [comment]
Fix included in https://github.com/IggyLabs/IggyLabsModules/releases/tag/v1.0.1 and will be in the library when the patch is accepted.
