### ISSUE TITLE
Table incorrectly zero-pads wavetables of any import length option to be 2048

### ISSUE THREAD

**Issue by paulpiko** [IggyLabs/IggyLabsModules#14]
The table manual says WaveEdit creates 512 samples/cycle files. I used the default settings in WaveEdit to create a wavetable (all sines). Only when loaded at 2048 did it table produce a continuous wave.
<img width="247" alt="table512" src="https://user-images.githubusercontent.com/56526215/87115427-95209b80-c2b6-11ea-93c9-13e5227a4cb0.PNG">
<img width="247" alt="table2048" src="https://user-images.githubusercontent.com/56526215/87115425-93ef6e80-c2b6-11ea-88ed-4177f2ea301f.PNG">

**Comment by isabelgk** [comment]
This is a mistake in the manual; WaveEdit creates table lengths of 256 samples. Can you try using the 256 import?

**Comment by paulpiko** [comment]
It's worse loading via 256, only one cycle

![image](https://user-images.githubusercontent.com/56526215/87116504-4d4f4380-c2b9-11ea-83be-b6930d7cc090.png)

**Comment by isabelgk** [comment]
Hmmm can you share the sample with me?

**Comment by isabelgk** [comment]
Ah wait, I think I might know the issue. I'll have to wait until tomorrow to try it.

**Comment by paulpiko** [comment]
The wave file...

[test.zip](https://github.com/IggyLabs/IggyLabsModules/files/4900809/test.zip)

**Comment by isabelgk** [comment]
If you can, could you try the latest build for your system with the fix implemented (see below)? Looks good with a bunch of tables I tested out. 

[IggyLabsModules-1.0.b95f16c-lin-20200710.zip](https://github.com/IggyLabs/IggyLabsModules/files/4901503/IggyLabsModules-1.0.b95f16c-lin-20200710.zip)
[IggyLabsModules-1.0.b95f16c-mac.zip](https://github.com/IggyLabs/IggyLabsModules/files/4901504/IggyLabsModules-1.0.b95f16c-mac.zip)
[IggyLabsModules-1.0.b95f16c-win.zip](https://github.com/IggyLabs/IggyLabsModules/files/4901505/IggyLabsModules-1.0.b95f16c-win.zip)

**Comment by paulpiko** [comment]
I think you've fixed it! Looks good on first tests here. Thanks.

**Comment by isabelgk** [comment]
Great! Fix should be updated in the library very shortly.
