### ISSUE TITLE
Table's position problem with reproducing wave

### ISSUE THREAD

**Issue by paulpiko** [IggyLabs/IggyLabsModules#15]
I create a WaveEdit wavetable, all triangles except the last one square (attached). I loaded it at 2048 since that produces a continuous wave, and moved pos to the most clockwise position. Rather than get just the square wave it was a mixture of square and triangle.

![image](https://user-images.githubusercontent.com/56526215/87115770-87b7e100-c2b7-11ea-8694-d88fa3978647.png)

[testtri.zip](https://github.com/IggyLabs/IggyLabsModules/files/4900750/testtri.zip)

**Comment by isabelgk** [comment]
Merging this issue with #14
