### ISSUE TITLE
Flipped Wave in Table

### ISSUE THREAD

**Issue by Petervos2018** [IggyLabs/IggyLabsModules#33]
As I said here : 

https://community.vcvrack.com/t/potato-chips-opinions-on-wavetable-synthesis/10657/12?u=yeager

![afbeelding](https://user-images.githubusercontent.com/46076474/89232737-5bf2f700-d5e8-11ea-9a3e-cbb59a618985.png)

Here is the file with the wavetable sample.

[Flipping Iggy - 04082020.zip](https://github.com/IggyLabs/IggyLabsModules/files/5019072/Flipping.Iggy.-.04082020.zip)

Greetings,

Peter

**Comment by isabelgk** [comment]
Thanks for reporting!

I'll have a fix out in the next release:

![image](https://user-images.githubusercontent.com/13615209/89238247-06542580-d5bb-11ea-9f3d-f52a5b623108.png)

**Comment by Petervos2018** [comment]
Bravo, your testing setup looks familiar ;)
Greetings,
Peter.
