### ISSUE TITLE
v2: Invalid URLs in manifest

### ISSUE THREAD

**Issue by cschol** [IggyLabs/IggyLabsModules#36]
In preparation for `v2` integration I am running integration test on select plugins.

```
[IggyLabsModules] Validating plugin.json...         
Exception validating URL: https://github.com/IggyLabs/IggyLabsModulesManual (HTTP Error 404: Not Found)
FAILED                 
[IggyLabsModules] Issues found in `plugin.json`:   
                                                                             
Invalid URL: https://github.com/IggyLabs/IggyLabsModulesManual
```

**Comment by isabelgk** [comment]
Hi @cschol ,

Can you update the reference in the library to the following commit? It should resolve the URL error.

`91e9bcdde24ef6d32a14308ea83da562fb914a1d`

**Comment by cschol** [comment]
We are now open for submission to the Library for `v2`. When you are ready to submit your `v2` version to the library, please let us know in this issue: https://github.com/VCVRack/library/issues/654

Thank you!
